version: '3.8'

services:

  redis-daemon:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes: 
      - cache:/data
    networks:
      - redis-network

volumes:
  cache:
    driver: local

networks:
  redis-network:
    name: redis-network